### ISSUE TITLE
Thought: More compliant defaults

### ISSUE THREAD

**Issue by qpwo** [quilicicf/markdown-formatter#151]
`prettier`, `tidy-markdown`, and github's editor buttons  use single-underscore italics and double-asterisk bolds. Having those as defaults would yield smaller diffs when `markdown-formatter` is applied to existing repos. I imagine you've thought about this already, but thought I'd mention it in case not.

**Comment by quilicicf** [comment]
I'm aware of this and people can setup markdown-formatter to comply if they so wish.

I set the current defaults because:
* using a mix of italics/bold is IMO at best not necessary. When I'm tempted to do so, I usually re-write the paragraph to make it clearer without mixing those (and I'm sure typography experts would find it terrible too)
* since there's no mix in my documents, using only underscores is IMO better because it's never ambiguous with bullet points that already use `*`
* most editors (and all of those I use) add italics/bold to the text while you're typing, so it's usually not an issue to tell italics and bold apart
* I have no intention to follow any loosely defined standards (more like conventions), the default here is my personal preference

For all these reasons, I'll keep the defaults as they are.

Thanks for pointing it though, will make it clearer should anyone else wonder about this.
